services:
    mysql:
        image: mysql
        restart: always
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=palyakovetes
    phpmyadmin:
        image: phpmyadmin
        restart: always
        depends_on:
            - mysql
        links:
            - mysql:db
        ports:
            - 8080:80
    backend:
        build:
            context: ./backend
        depends_on:
            - mysql
        ports:
            - 3000:3000
        environment:
            PORT: 3000
            NODE_ENV: development
            JWT_SECRET: titok
            JWT_LIFETIME: 900
            COOKIE_SECRET: titok
            COOKIE_MAX_AGE: 900
        volumes:
            - ./backend/src:/app/src
        command:
            [
                "sh",
                "-c",
                "while ! nc -z mysql 3306; do sleep 1; done; npx prisma db push && npx prisma db seed"
            ]
    frontend:
        build:
            context: ./frontend
        restart: always
        depends_on:
            - backend
        ports:
            - 5173:5173
        volumes:
            - ./frontend/src:/app/src
