openapi: "3.0.3"
info:
    title: API dokumentáció
    description: Pályakövető rendszer Swagger dokumentációja
    version: "2.0"
servers:
    - url: http://localhost:8080/api
paths:
    /auth/register:
        post:
            tags: ["Auth"]
    /auth/login:
        post:
            tags: ["Auth"]
    /auth/logout:
        post:
            tags: ["Auth"]
    /schools:
        get:
            tags: ["School"]
            responses:
                "200":
                    description: Get the list of schools
components:
    securitySchemes:
        bearerAuth: # arbitrary name for the security scheme
            type: http
            scheme: bearer
            bearerFormat: JWT
